import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container } from "styled-system/jsx";
import { Sidebar, type SidebarData } from "./_components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sidebar: SidebarData = [
  {
    title: "概要",
    pages: [{ name: "イントロダクション", path: "/" }],
  },
  {
    title: "CSS",
    pages: [{ name: "セレクターの基本", path: "/css/basic-selectors" }],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container
          my={12}
          maxWidth="6xl"
          display="grid"
          gridTemplateColumns="auto 1fr"
          gap={{
            base: 2,
            md: 4,
            lg: 6,
          }}
        >
          <Sidebar data={sidebar} />
          {children}
        </Container>
      </body>
    </html>
  );
}
